=== uiii/pw-test/src/file/config/schema.json
{
	"$schema": "http://json-schema.org/schema#",

	"type": "object",

	"properties": {
		"tmpDir": {
			"type": "string",
			"minLength": 1
		},

		"db": {
			"type": "object",
			"properties": {
				"host": { "type": "string" },
				"port": { "type": "number" },
				"user": { "type": "string" },
				"pass": { "type": "string" },
				"name": { "type": "string" }
			}
		},

		"testTags": {
			"type": "array",
			"items": {
				"type": "string",
				"minLength": 1
			}
		},

		"copySources": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"destination": {
						"type": "string",
						"minLength": 1
					},
					"source": {
						"oneOf": [
							{
								"type": "string",
								"minLength": 1
							},
							{
								"type": "array",
								"items": {
									"type": "string",
									"minLength": 1
								},
								"minItems": 1
							}
						]
					}
				},
				"required": [
					"destination",
					"source"
				]
			}
		},

		"testCmd": {
			"type": "string"
		},

		"waitAfterTests": {
			"type": "string",
			"enum": ["never", "onFailure", "always"]
		}
	},

	"required": [
		"tmpDir",
		"db",
		"testTags",
		"copySources",
		"testCmd",
		"waitAfterTests"
	]
}

=== uiii/pw-test/tests/fixture/valid_partial_config.json
{
    "tmpDir": ".pw-test",

    "db": {
        "host": "localhost",
        "port": 3306,
        "user": "root",
        "pass": "",
        "name": "pw_test"
    },

    "testTags": [
        "2.7",
        "3.0"
    ],

    "copySources": [
        {
            "destination": "site/modules/Module",
            "source": [
                "Module.module",
                "file.php"
            ]
        },
        {
            "destination": "site/template/template.php",
            "source": "template.php"
        }
    ],

    "testCmd": "vendor/bin/phpunit",

    "waitAfterTests": "never"
}
